INSERT INTO RAW.H_STOCK (
	STOCK_KEY,
	LOAD_DATE,
	RECORD_SOURCE,
	STOCK_SYMBOL
)
SELECT DISTINCT
	STOCK_SYMBOL_KEY,
	LOAD_DATE,
	STRING_AGG(record_source) AS RECORD_SOURCE,
	STOCK_SYMBOL_BUSINESS_KEY
FROM 
	STAGE.STAGE_STOCK_COMBINED_VIEW
WHERE
	STOCK_SYMBOL_KEY <> '00000000000000000000000000000000' AND
	NOT EXISTS (
		SELECT 1
		FROM RAW.H_STOCK 
		WHERE H_STOCK.STOCK_KEY = STAGE_STOCK_COMBINED_VIEW.STOCK_SYMBOL_KEY
	)
GROUP BY STOCK_SYMBOL_KEY,LOAD_DATE,STOCK_SYMBOL_BUSINESS_KEY
;