UPDATE
	RAW.S_STOCK_STATUS
SET 
	LOAD_END_DATE = STAGE_STOCK_COMBINED_VIEW.LOAD_DATE,
	IS_CURRENT = FALSE
FROM
	STAGE.STAGE_STOCK_COMBINED_VIEW
WHERE 
	STAGE_STOCK_COMBINED_VIEW.STOCK_SYMBOL_KEY = S_STOCK_STATUS.STOCK_KEY AND
	S_STOCK_STATUS.IS_CURRENT AND
	NOT S_STOCK_STATUS.IS_ACTIVE
;