INSERT INTO RAW.S_STOCK_STATUS (
	STOCK_KEY,
	LOAD_DATE,
	LOAD_END_DATE,
	IS_CURRENT,
	RECORD_SOURCE,
	IS_ACTIVE
)
SELECT DISTINCT
	H_STOCK.STOCK_KEY,
	(SELECT MAX(LOAD_DATE) FROM STAGE.STAGE_STOCK_COMBINED_VIEW),
	'9999-01-01'::TIMESTAMP,
	TRUE,
	(SELECT MAX(SPLIT_PART(record_source , '_', 2)) FROM STAGE.STAGE_STOCK_COMBINED_VIEW),
	FALSE
FROM
	RAW.H_STOCK
LEFT OUTER JOIN
	STAGE.STAGE_STOCK_COMBINED_VIEW ON
		STAGE_STOCK_COMBINED_VIEW.STOCK_SYMBOL_KEY = H_STOCK.STOCK_KEY
WHERE
	(STAGE_STOCK_COMBINED_VIEW.STOCK_SYMBOL_KEY IS NULL OR STAGE_STOCK_COMBINED_VIEW.STOCK_SYMBOL_KEY <> H_STOCK.STOCK_KEY) AND
	NOT EXISTS (
		SELECT 1
		FROM RAW.S_STOCK_STATUS
		WHERE
			S_STOCK_STATUS.STOCK_KEY = H_STOCK.STOCK_KEY AND
			S_STOCK_STATUS.IS_CURRENT
	)
;