INSERT INTO RAW.S_STOCK_DATE (
	STOCK_DATE_LINK_KEY ,
	LOAD_DATE ,
	LOAD_END_DATE ,
	IS_CURRENT ,
	RECORD_SOURCE ,
	PRICE 
)
SELECT DISTINCT
	STOCK_DATE_LINK_KEY,
	LOAD_DATE,
	'9999-01-01'::TIMESTAMP,
	TRUE,
	SPLIT_PART(record_source , '_', 2) AS RECORD_SOURCE,	
	PRICE
FROM 
	STAGE.STAGE_STOCK_COMBINED_VIEW
WHERE
	NOT EXISTS (
		SELECT 1
		FROM RAW.S_STOCK_DATE
		WHERE
			S_STOCK_DATE.STOCK_DATE_LINK_KEY = STAGE_STOCK_COMBINED_VIEW.STOCK_DATE_LINK_KEY AND
			S_STOCK_DATE.PRICE = STAGE_STOCK_COMBINED_VIEW.PRICE AND 
			S_STOCK_DATE.IS_CURRENT
	)
;