UPDATE
	RAW.S_STOCK_DATE
SET 
	LOAD_END_DATE = STAGE_STOCK_COMBINED_VIEW.LOAD_DATE,
	IS_CURRENT = FALSE
FROM
	STAGE.STAGE_STOCK_COMBINED_VIEW
WHERE 
	STAGE_STOCK_COMBINED_VIEW.STOCK_DATE_LINK_KEY = S_STOCK_DATE.STOCK_DATE_LINK_KEY AND
	STAGE_STOCK_COMBINED_VIEW.PRICE <> S_STOCK_DATE.PRICE AND
	S_STOCK_DATE.IS_CURRENT
;