CREATE VIEW STAGE.STAGE_STOCK_COMBINED_VIEW AS
   WITH combined_cte AS
(
SELECT 	
	STOCK_SYMBOL,
	DATE,
	PRICE,
	LOAD_DATE,
	RECORD_SOURCE,
	STOCK_SYMBOL_BUSINESS_KEY,
	STOCK_SYMBOL_KEY,
	DATE_BUSINESS_KEY,
	DATE_KEY,
	STOCK_DATE_LINK_KEY 
FROM stage.stage_upstox_stock
UNION ALL
SELECT 	
	STOCK_SYMBOL,
	DATE,
	PRICE,
	LOAD_DATE,
	RECORD_SOURCE,
	STOCK_SYMBOL_BUSINESS_KEY,
	STOCK_SYMBOL_KEY,
	DATE_BUSINESS_KEY,
	DATE_KEY,
	STOCK_DATE_LINK_KEY 
FROM stage.stage_bse_stock
),
rank_date_sym AS
(
SELECT 	
	STOCK_SYMBOL,
	DATE,
	PRICE,
	LOAD_DATE,
	RECORD_SOURCE,
	STOCK_SYMBOL_BUSINESS_KEY,
	STOCK_SYMBOL_KEY,
	DATE_BUSINESS_KEY,
	DATE_KEY,
	STOCK_DATE_LINK_KEY,
	ROW_NUMBER () OVER (PARTITION BY STOCK_SYMBOL_BUSINESS_KEY,DATE_BUSINESS_KEY ORDER BY LOAD_DATE DESC) AS latest_rec
FROM combined_cte
)
SELECT * FROM rank_date_sym
WHERE latest_rec=1
;