CREATE TABLE IF NOT EXISTS RAW.S_STOCK_DATE (
	STOCK_DATE_LINK_KEY CHAR(32) NOT NULL,
	LOAD_DATE TIMESTAMP NOT NULL,
	LOAD_END_DATE TIMESTAMP NOT NULL,
	IS_CURRENT BOOLEAN NOT NULL,
	RECORD_SOURCE VARCHAR,
	PRICE NUMERIC,
	PRIMARY KEY (STOCK_DATE_LINK_KEY, LOAD_DATE, IS_CURRENT),
	FOREIGN KEY (STOCK_DATE_LINK_KEY) REFERENCES RAW.L_STOCK_DATE (STOCK_DATE_LINK_KEY)
);