CREATE TABLE IF NOT EXISTS RAW.S_STOCK_STATUS (
  STOCK_KEY CHAR(32) NOT NULL,
  LOAD_DATE TIMESTAMP NOT NULL,
  LOAD_END_DATE TIMESTAMP NOT NULL,
  IS_CURRENT BOOLEAN NOT NULL,
  RECORD_SOURCE VARCHAR NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL,
  PRIMARY KEY (STOCK_KEY, LOAD_DATE),
  FOREIGN KEY (STOCK_KEY) REFERENCES RAW.H_STOCK (STOCK_KEY)
);